// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/(dashboard)/automations/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/automations/[id]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/automations/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/automations/[id]/logs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/automations/[id]/logs">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/automations/[id]/logs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/automations/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/automations/new">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/automations/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/automations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/automations">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/automations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/broadcasts/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/broadcasts/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/broadcasts/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/broadcasts/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/broadcasts/new">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/broadcasts/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/broadcasts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/broadcasts">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/broadcasts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/companies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/companies">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/companies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/contacts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contacts">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/contacts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/inbox/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inbox">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/inbox/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/ivr/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ivr/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/ivr/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/ivr/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ivr">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/ivr/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/pipelines/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pipelines">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/pipelines/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/tasks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tasks">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/tasks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/zenith-calls/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/zenith-calls">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/zenith-calls/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/zenith-login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/zenith-login">> = Specific
  const handler = {} as typeof import("../../src/app/zenith-login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/account/members/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/account/members">> = Specific
  const handler = {} as typeof import("../../src/app/api/account/members/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/zenith/context/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/zenith/context">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/zenith/context/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/zenith/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/zenith/login">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/zenith/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/zenith/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/zenith/logout">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/zenith/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/zenith/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/zenith/me">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/zenith/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/health/live/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health/live">> = Specific
  const handler = {} as typeof import("../../src/app/api/health/live/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/health/ready/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health/ready">> = Specific
  const handler = {} as typeof import("../../src/app/api/health/ready/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/internal/voice/wacalls/channels/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/internal/voice/wacalls/channels">> = Specific
  const handler = {} as typeof import("../../src/app/api/internal/voice/wacalls/channels/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/webhooks/zenith/evolution/[channelId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/zenith/evolution/[channelId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/webhooks/zenith/evolution/[channelId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/webhooks/zenith/meta/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/zenith/meta">> = Specific
  const handler = {} as typeof import("../../src/app/api/webhooks/zenith/meta/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/webhooks/zenith/test-inbound/[channelId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/zenith/test-inbound/[channelId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/webhooks/zenith/test-inbound/[channelId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/webhooks/zenith/voice/wacalls/[channelId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/zenith/voice/wacalls/[channelId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/webhooks/zenith/voice/wacalls/[channelId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/zenith/activities/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/zenith/activities">> = Specific
  const handler = {} as typeof import("../../src/app/api/zenith/activities/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/zenith/automations/[id]/logs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/zenith/automations/[id]/logs">> = Specific
  const handler = {} as typeof import("../../src/app/api/zenith/automations/[id]/logs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/zenith/automations/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/zenith/automations/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/zenith/automations/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/zenith/automations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/zenith/automations">> = Specific
  const handler = {} as typeof import("../../src/app/api/zenith/automations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/zenith/broadcasts/[id]/cancel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/zenith/broadcasts/[id]/cancel">> = Specific
  const handler = {} as typeof import("../../src/app/api/zenith/broadcasts/[id]/cancel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/zenith/broadcasts/[id]/recipients/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/zenith/broadcasts/[id]/recipients">> = Specific
  const handler = {} as typeof import("../../src/app/api/zenith/broadcasts/[id]/recipients/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/zenith/broadcasts/[id]/retry/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/zenith/broadcasts/[id]/retry">> = Specific
  const handler = {} as typeof import("../../src/app/api/zenith/broadcasts/[id]/retry/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/zenith/broadcasts/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/zenith/broadcasts/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/zenith/broadcasts/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/zenith/broadcasts/[id]/start/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/zenith/broadcasts/[id]/start">> = Specific
  const handler = {} as typeof import("../../src/app/api/zenith/broadcasts/[id]/start/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/zenith/broadcasts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/zenith/broadcasts">> = Specific
  const handler = {} as typeof import("../../src/app/api/zenith/broadcasts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/zenith/calls/[id]/action/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/zenith/calls/[id]/action">> = Specific
  const handler = {} as typeof import("../../src/app/api/zenith/calls/[id]/action/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/zenith/calls/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/zenith/calls/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/zenith/calls/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/zenith/calls/[id]/webrtc/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/zenith/calls/[id]/webrtc">> = Specific
  const handler = {} as typeof import("../../src/app/api/zenith/calls/[id]/webrtc/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/zenith/calls/incoming/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/zenith/calls/incoming">> = Specific
  const handler = {} as typeof import("../../src/app/api/zenith/calls/incoming/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/zenith/calls/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/zenith/calls">> = Specific
  const handler = {} as typeof import("../../src/app/api/zenith/calls/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/zenith/companies/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/zenith/companies/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/zenith/companies/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/zenith/companies/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/zenith/companies">> = Specific
  const handler = {} as typeof import("../../src/app/api/zenith/companies/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/zenith/contacts/[id]/custom-fields/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/zenith/contacts/[id]/custom-fields">> = Specific
  const handler = {} as typeof import("../../src/app/api/zenith/contacts/[id]/custom-fields/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/zenith/contacts/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/zenith/contacts/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/zenith/contacts/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/zenith/contacts/[id]/tags/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/zenith/contacts/[id]/tags">> = Specific
  const handler = {} as typeof import("../../src/app/api/zenith/contacts/[id]/tags/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/zenith/contacts/bulk/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/zenith/contacts/bulk">> = Specific
  const handler = {} as typeof import("../../src/app/api/zenith/contacts/bulk/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/zenith/contacts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/zenith/contacts">> = Specific
  const handler = {} as typeof import("../../src/app/api/zenith/contacts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/zenith/conversations/[id]/messages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/zenith/conversations/[id]/messages">> = Specific
  const handler = {} as typeof import("../../src/app/api/zenith/conversations/[id]/messages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/zenith/conversations/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/zenith/conversations/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/zenith/conversations/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/zenith/conversations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/zenith/conversations">> = Specific
  const handler = {} as typeof import("../../src/app/api/zenith/conversations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/zenith/custom-fields/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/zenith/custom-fields/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/zenith/custom-fields/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/zenith/custom-fields/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/zenith/custom-fields">> = Specific
  const handler = {} as typeof import("../../src/app/api/zenith/custom-fields/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/zenith/dashboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/zenith/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/api/zenith/dashboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/zenith/deals/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/zenith/deals/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/zenith/deals/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/zenith/deals/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/zenith/deals">> = Specific
  const handler = {} as typeof import("../../src/app/api/zenith/deals/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/zenith/inbox/events/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/zenith/inbox/events">> = Specific
  const handler = {} as typeof import("../../src/app/api/zenith/inbox/events/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/zenith/ivr-flows/[id]/draft/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/zenith/ivr-flows/[id]/draft">> = Specific
  const handler = {} as typeof import("../../src/app/api/zenith/ivr-flows/[id]/draft/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/zenith/ivr-flows/[id]/publish/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/zenith/ivr-flows/[id]/publish">> = Specific
  const handler = {} as typeof import("../../src/app/api/zenith/ivr-flows/[id]/publish/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/zenith/ivr-flows/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/zenith/ivr-flows/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/zenith/ivr-flows/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/zenith/ivr-flows/[id]/validate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/zenith/ivr-flows/[id]/validate">> = Specific
  const handler = {} as typeof import("../../src/app/api/zenith/ivr-flows/[id]/validate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/zenith/ivr-flows/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/zenith/ivr-flows">> = Specific
  const handler = {} as typeof import("../../src/app/api/zenith/ivr-flows/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/zenith/messaging-channels/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/zenith/messaging-channels/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/zenith/messaging-channels/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/zenith/messaging-channels/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/zenith/messaging-channels">> = Specific
  const handler = {} as typeof import("../../src/app/api/zenith/messaging-channels/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/zenith/notes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/zenith/notes">> = Specific
  const handler = {} as typeof import("../../src/app/api/zenith/notes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/zenith/pipelines/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/zenith/pipelines/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/zenith/pipelines/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/zenith/pipelines/[id]/stages/[stageId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/zenith/pipelines/[id]/stages/[stageId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/zenith/pipelines/[id]/stages/[stageId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/zenith/pipelines/[id]/stages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/zenith/pipelines/[id]/stages">> = Specific
  const handler = {} as typeof import("../../src/app/api/zenith/pipelines/[id]/stages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/zenith/pipelines/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/zenith/pipelines">> = Specific
  const handler = {} as typeof import("../../src/app/api/zenith/pipelines/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/zenith/tags/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/zenith/tags/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/zenith/tags/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/zenith/tags/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/zenith/tags">> = Specific
  const handler = {} as typeof import("../../src/app/api/zenith/tags/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/zenith/tasks/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/zenith/tasks/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/zenith/tasks/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/zenith/tasks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/zenith/tasks">> = Specific
  const handler = {} as typeof import("../../src/app/api/zenith/tasks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/zenith/voice-channels/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/zenith/voice-channels/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/zenith/voice-channels/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/zenith/voice-channels/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/zenith/voice-channels">> = Specific
  const handler = {} as typeof import("../../src/app/api/zenith/voice-channels/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/zenith/workers/automation-dispatcher/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/zenith/workers/automation-dispatcher">> = Specific
  const handler = {} as typeof import("../../src/app/api/zenith/workers/automation-dispatcher/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/zenith/workers/automation-outbox-sweep/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/zenith/workers/automation-outbox-sweep">> = Specific
  const handler = {} as typeof import("../../src/app/api/zenith/workers/automation-outbox-sweep/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/zenith/workers/broadcast-dispatcher/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/zenith/workers/broadcast-dispatcher">> = Specific
  const handler = {} as typeof import("../../src/app/api/zenith/workers/broadcast-dispatcher/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/(dashboard)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
